language: elixir
elixir:
  - 1.6.6
  - 1.7.4
  - 1.8.0
otp_release:
  - 19.3
  - 20.3
  - 21.2
matrix:
  exclude:
    - elixir: 1.8.0
      otp_release: 19.3
install: true
script:
  - mix local.rebar --force
  - mix local.hex --force
  - make distclean
  - make dist
