language: elixir
elixir:
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
otp_release:
  - 19.1
  - 19.0
  - 18.3
  - 18.1
  - 18.0
install: true
script:
  - mix local.rebar --force
  - mix local.hex --force
  - make distclean
  - make dist
